import { Country } from './country';

export const COUNTRIES: Country[] = [
    {
        Country: 'pais1',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais2',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais3',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais4',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais5',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais6',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais7',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    },
    {
        Country: 'pais8',
        NewConfirmed: 15,
        TotalConfirmed: 158,
        NewDeaths: 1,
        TotalDeaths: 12,
        NewRecovered: 56,
        TotalRecovered: 94,
    }
];
